Repository json5/json5, pull requests merged in 2019-10, with the labels that each got.

#196 Correct spelling mistakes
  CONTRIBUTING.md
  README.md
  test/errors.js
Labels: documentation :page_facing_up:

#208 Add module entry to package.json
  package.json
Labels: enhancement :+1:

#210 fix: stringify `\0` as `\\x00` in some cases
  lib/stringify.js
  test/stringify.js
Labels: bug :bug:
